### ISSUE TITLE
Support for APP-6(B)

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-symbology#225]
### Tasks: 
- [ ] Turn this issue into an Epic
- [ ] Add tasks to this epic that are broken down as simple as possible

### Development 

Create a datamodel to allow us to add the stylx file to MSE (similar to 2525-D )
- [ ] Modifications to the app6b dictionary renderer to use attribute fields (similar to how the previous mil2525c renderer was changed for mil2525c_b2 renderer) 
- [ ] stylx design
- [ ] GDB schema
- [ ] Updated app6b dictionary renderer is available in Pro
- [ ] layer package using updated app6b dictionary renderer 
- [ ] implement in the Military Symbol Editor once available in Pro, and layer package available

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#86
