### ISSUE TITLE
Support for APP-6(D)

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-symbology#226]
Currently the MSE only supports 2525. Updates are required to the Military Symbol Editor to support APP-6(D).

**Note: This depends on Pro 2.2 which contains the app6d dictionary renderer/stylx** 

### Tasks: 

- [x] Turn this issue into an Epic
- [ ] Add tasks to this epic that are broken down as simple as possible

### Development 

Create a datamodel to allow us to add the stylx file to MSE (similar to 2525-D )
- [x] stylx design - app6d stylx available in Pro 2.2 Install
- [ ] GDB schema - that adds Dismounted (Infantry) Feature Class to existing 2525D GDB
- [ ] Schema-only layer package that (1) Contains App6D GDB and (2) Layers using APP6D Dictionary Renderer named "MilitaryOverlay-app6d.lpkx"

**Comment by csmoore** [comment]
As part of researching this task, the proposed code changes were implemented in branch: https://github.com/Esri/military-symbol-editor-addin-wpf/tree/csm/%23226-app6d-support 

In the general the changes required/impacts are:

1. Adding APP6D to the settings form:

![app6d-newsettingswindow](https://user-images.githubusercontent.com/3090809/43971229-495f0b2c-9c9e-11e8-846c-33d66614bc26.PNG)

2. Adding a new layer/feature class for the Dismounted Infantry (and associated domains):

![app6d-newlayer](https://user-images.githubusercontent.com/3090809/43971239-54a6849c-9c9e-11e8-8836-f701a8896687.PNG)

3. Creating/adding a new APP6D "MilitaryOverlay-app6d.lpkx" that contains this new layer and used the using APP6D Dictionary Renderer:

![app6d-newlayerpackage](https://user-images.githubusercontent.com/3090809/43971264-6c37f9d8-9c9e-11e8-965e-f7fc770aa6f1.PNG)

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#87
