### ISSUE TITLE
APP-6(D) Dictionary/Stylx

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#288]
_From @lfunkhouser on January 19, 2018 15:57_

Support for APP-6(D) is needed for compliance with NATO systems.
The APP-6(D) dictionary will support Runtime and ArcGIS Pro.

(Updated with potential tasks/plan)

### Preparation

- [ ] Identify the set of differences between APP-6(D) and MIL-STD-2525D

### Stylx (Icons)

- [ ] Update stylx creation process to use Pro 2.0
    * Create Pro App/Addin to directly create stylx from SVG icons 
    * Now that Pro 2.0 directly supports adding SVGs to styles
    * To update/replace [the old Pro 1.0 process which is overly complex and relied on ArcMap/EMFs/etc.](https://github.com/Esri/military-features-data/tree/dev/military-symbology-styles/utils-and-source-data/style-creation-utilities#style-creation-utilities)
- [ ] Create Stylx with new App6D icons (Dismounted Symbol Set)
- [ ] Copy new icons to 2525D stylx to create App6d stylx
- [ ] Test new App6D stylx
- [ ] Provide to RT, Create DT issue to update Renderer

### Stylx (Labels)

- [ ] Identify Label deltas from 2525D.0 -> App6d.1 for each symbol set
- [ ] Edit/Update Label Rules in stylx
    * Note: there is not yet a UI in Pro to do this, so needs done manually
    * This work can be done after the stylx is provide to RT

### Dictionary Renderer

- [ ] Coordinate updates with Core
- [ ] Test in Runtime
- [ ] Test in Pro
    
___

**The other tasks below are not needed for the stylx creation, but are part of testing the overall solution**

### GDB 

- [ ] Identify any changes from the 2525D datamodel -> App6D
- [ ] Edit the [datamodel source csvs](https://github.com/Esri/military-features-data/tree/csm/app6d-dev/military-overlay/utils-source-and-test-data/schema-source-files/app6d) with the changes
- [ ] Generate new App6d gdb

### Military Overlay

- [ ] Update Military Overlay to add App6d, new dismounted symbol set layer
- [ ] Once Render available, test in Pro

### Pro Symbol Editor

- [ ] Update Symbol Editor Addin to support App6D

_Copied from original issue: Esri/military-features-data#293_

**Comment by topowright** [comment]
_From @csmoore on January 23, 2018 21:26_

@lfunkhouser @joebayles - do we have:

1. The final version of the standard (or is Study Draft 2, JUNE 2016 the final version) 
2. A list of differences from 2525D
3. The image files (SVGs) that were added to/changed in the APP-6D Version 1 from 2525D final?

I believe the added image files were confined to:

1. New Dismounted Individual symbol set 
2. Symbol set/battle dimension frames that changed 
3. Some symbol differences

This question might be premature, but thought I'd ask just in case there is a long lead time requesting/obtaining

**Comment by topowright** [comment]
_From @joebayles on January 25, 2018 15:9_

@csmoore we have the final version of APP-6D in [Box](https://esri.app.box.com/file/240334755915). I believe you are correct with everything else. Check https://github.com/Esri/joint-military-symbology-xml/pull/396 for the SVGs.

**Comment by topowright** [comment]
_From @csmoore on February 7, 2018 15:52_

Just to update this task - when I looked this a couple weeks ago - here is what I found and updated

The changes from 2525D.0 (06/2014) to App6D.1 (10/2017) that were readily identifiable by just skimming the standard were:

1.	Small Changes to the labels associated with each symbol set (screenshot below). Ex. country label added
2.	Addition of Dismounted Individual Symbol Set (Set 27)
3.	Addition of a new Dimension/Identity Frame Type for Dismounted Individual (Hexagon Frame for Friendly)
4.	Addition of a new Echelon Mobility Amplifier (SIDC Digits 9 & 10) for Dismounted Individual Leadership Indicator

While I was reviewing his, I went ahead and made the data updates I thought would be required for items 2-4) in branch:  https://github.com/Esri/military-features-data/tree/csm/app6d-dev - To see/understand the primary changes needed, look at this commit:  https://github.com/Esri/military-features-data/commit/615e4b05dd29376fefd22da8a488520d20d6e179 

So this should be ready to at least attempt going through the process of [creating the style](https://github.com/Esri/military-features-data/tree/dev/military-symbology-styles/utils-and-source-data/style-creation-utilities) and [datamodel/GDB](https://github.com/Esri/military-features-data/tree/dev/military-overlay/utils-source-and-test-data) with this branch.

Also while reviewing the PR mentioned above I noticed some issues that might prevent using the JMSML source data - https://github.com/Esri/joint-military-symbology-xml/pull/396#issuecomment-361315594 but that repo/data is not needed at this time with the manual changes made in https://github.com/Esri/military-features-data/commit/615e4b05dd29376fefd22da8a488520d20d6e179 

Example Frame Label Differences:

![image](https://user-images.githubusercontent.com/3090809/35924586-75bdaa5e-0bf1-11e8-966e-a7b14aad46a1.png)

**Comment by topowright** [comment]
_From @csmoore on February 24, 2018 1:1_

Note: Updated the original issue [comment above](https://github.com/Esri/military-features-data/issues/293#issue-290022266) with high-level plan, potential subtasks, etc.

**Comment by topowright** [comment]
_From @csmoore on March 8, 2018 17:48_

This is in the [Sprint plan](https://github.com/ArcGIS/solutions-defense/wiki/Release-2018-April#sprint-6-mar-07---mar-13) so going to move in progress and verify there are no issues creating a style with the latest SVGs using **Pro** only.

**Comment by topowright** [comment]
_From @lfunkhouser on March 8, 2018 21:55_

@csmoore This is an epic and needs to be broken down into issues not just pulled in and worked on. There is no understanding among the team of what this issue means. The high-level plan needs to be broken down into manageable issues that can be worked on and closed out.

**Comment by topowright** [comment]
_From @csmoore on March 9, 2018 12:17_

@lfunkhouser - OK - I was just going to work on the first task above "Update stylx creation process to use Pro 2.0" but can wait until this complete item is planned+ready to work on - moving task back

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#88
