### ISSUE TITLE
Adding symbol id codes to the output feature class 

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#317]
#### Tasks  to be done: 

2525D
- [ ] Add symbol id code to feature class schema
- [ ] auto populate symbol id code for each symbol into feature class
- [ ] Verfiy changes

APP6D

- [ ] Add symbol id code to feature class schema
- [ ] auto populate symbol id code for each symbol into feature class
- [ ] Verfiy changes

2525 C

- [ ] Add symbol id code to feature class schema
- [ ] auto populate symbol id code for each symbol into feature class
- [ ] Verfiy changes

APP6B

- [ ] Add symbol id code to feature class schema
- [ ] auto populate symbol id code for each symbol into feature class
- [ ] Verfiy changes

- [ ] Add to whats new
- [ ] Add to issues addressed
- [ ] Verify documentation changes

#### Background
Currently when a user creates a symbol in MSE they do not get a symbol id code in the created feature table

#### Expected Results
The output feature class has a symbol id code in the feature table

**Comment by topowright** [comment]
Being that this is a new capability I am logging this as a new feature even though it is a issue reported by customers. @lfunkhouser

**Comment by csmoore** [comment]
Just a note that it might be best to defer this issue until our minimum supported version in Pro 2.3 and we can [use attribute rules](https://pro.arcgis.com/en/pro-app/help/data/geodatabases/overview/an-overview-of-attribute-rules.htm) to calculate the SIDC at the feature/database level so this works even if the database is edited outside of the Symbol Editor.

**Comment by joebayles** [comment]
This is imperative for interoperability for our customers to work with other systems.

**Comment by dfoll** [comment]
Just an fyi, Was having a convo with @jfrygeo  and Armando today and this requirement came up again. 

Also, is this a duplicate of #184, or vice versa?
